# Generated by Django 4.2.2 on 2023-06-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0002_artwork_cafe_hotel_library_office_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/'),
        ),
    ]
