# Generated by Django 4.2.3 on 2023-07-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0002_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='selected_attractions',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='afternoon_attractions',
            field=models.ManyToManyField(related_name='afternoon_itineraries', to='gmaps.attractions'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='morning_attractions',
            field=models.ManyToManyField(related_name='morning_itineraries', to='gmaps.attractions'),
        ),
    ]
