# Generated by Django 4.2.2 on 2023-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0004_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attractions',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cafe',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='museum',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='office',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='zone',
            field=models.IntegerField(null=True),
        ),
    ]
