# Generated by Django 4.2.3 on 2023-07-17 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmaps', '0005_communityitinerary_useritinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityitinerary',
            name='joined_users',
            field=models.ManyToManyField(related_name='joined_itineraries', through='gmaps.UserItinerary', to=settings.AUTH_USER_MODEL),
        ),
    ]
