# Generated by Django 4.2.3 on 2023-07-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0005_artwork_tag_artwork_zone_attractions_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionRestaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaps.attractions')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaps.restaurant')),
            ],
            options={
                'db_table': 'attraction_restaurants',
            },
        ),
    ]
