# Generated by Django 4.2.3 on 2023-07-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0006_communityitinerary_joined_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='selected_restaurant',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='dinner_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_itineraries', to='gmaps.restaurant'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='lunch_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_itineraries', to='gmaps.restaurant'),
        ),
    ]
